language: python
python:
    - 3.7-dev
    - 3.6
    - 3.5
    - 3.4
    - 2.7

before_install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

script:
    - CFLAGS="-coverage" python setup.py build_ext --inplace
    - flake8 --max-line-length=110 *.py
    - nosetests -v --with-coverage --cover-package=boost_collections

after_success:
    - TRAVIS_JOB_ID=${TRAVIS_JOB_ID}C cpp-coveralls --build-root .
    - coveralls